name: Publish
on:
  workflow_call:
    inputs:
      public_publish:
        required: false
        type: string
        default: 'false'
      private_publish:
        required: false
        type: string
        default: 'false'
jobs:
  release:
    name: Release gem
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1
        if: ${{ inputs.public_publish == 'true' || inputs.private_publish == 'true' }}
        with:
          # Optional, will publish to RubyGems if specified
          api_key: ${{ inputs.public_publish == 'true' && secrets.RUBYGEMS_API_KEY }}
          # Optional, will publish to GitHub Packages if specified
          github_token: ${{ inputs.private_publish == 'true' && secrets.GITHUB_TOKEN }}
