name: release-please
on: [pull_request]

jobs:
  release-please:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ruby
          package-name: httpigeon
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
  publish-gem:
    uses: ./.github/workflows/publish.yaml
    needs: [ release-please ]
    with:
      publish: 'true'
      gem_version: "${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}"
